[2025-10-07T10:17:08.492+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-07T10:17:08.572+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: vnstock_weekly_etl_incremental.process_batch manual__2025-10-07T10:01:57.519057+00:00 map_index=34 [queued]>
[2025-10-07T10:17:08.642+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: vnstock_weekly_etl_incremental.process_batch manual__2025-10-07T10:01:57.519057+00:00 map_index=34 [queued]>
[2025-10-07T10:17:08.654+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 3
[2025-10-07T10:17:08.721+0000] {taskinstance.py:2890} INFO - Executing <Mapped(_PythonDecoratedOperator): process_batch> on 2025-10-07 10:01:57.519057+00:00
[2025-10-07T10:17:08.818+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=720) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-10-07T10:17:08.829+0000] {standard_task_runner.py:72} INFO - Started process 899 to run task
[2025-10-07T10:17:08.812+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'vnstock_weekly_etl_incremental', 'process_batch', 'manual__2025-10-07T10:01:57.519057+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpow36ajg0', '--map-index', '34']
[2025-10-07T10:17:08.833+0000] {standard_task_runner.py:105} INFO - Job 44: Subtask process_batch
[2025-10-07T10:17:08.897+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-07T10:17:10.125+0000] {task_command.py:467} INFO - Running <TaskInstance: vnstock_weekly_etl_incremental.process_batch manual__2025-10-07T10:01:57.519057+00:00 map_index=34 [running]> on host e3278e0f0bbc
[2025-10-07T10:17:10.501+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='vnstock_weekly_etl_incremental' AIRFLOW_CTX_TASK_ID='process_batch' AIRFLOW_CTX_EXECUTION_DATE='2025-10-07T10:01:57.519057+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-07T10:01:57.519057+00:00'
[2025-10-07T10:17:10.505+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-10-07T10:17:10.514+0000] {logging_mixin.py:190} INFO - ⚠️ Lỗi khi xử lý ACL: 'Limiter' object has no attribute 'ratelimit'
[2025-10-07T10:17:10.515+0000] {logging_mixin.py:190} INFO - ⚠️ Lỗi khi xử lý ACG: 'Limiter' object has no attribute 'ratelimit'
[2025-10-07T10:17:10.522+0000] {logging_mixin.py:190} INFO - ⚠️ Lỗi khi xử lý ACE: 'Limiter' object has no attribute 'ratelimit'
[2025-10-07T10:17:10.522+0000] {logging_mixin.py:190} INFO - ⚠️ Lỗi khi xử lý ACC: 'Limiter' object has no attribute 'ratelimit'
[2025-10-07T10:17:10.523+0000] {logging_mixin.py:190} INFO - ⚠️ Lỗi khi xử lý ACB: 'Limiter' object has no attribute 'ratelimit'
[2025-10-07T10:17:10.524+0000] {logging_mixin.py:190} INFO - ⚠️ Lỗi khi xử lý ABW: 'Limiter' object has no attribute 'ratelimit'
[2025-10-07T10:17:10.525+0000] {logging_mixin.py:190} INFO - ⚠️ Lỗi khi xử lý ABT: 'Limiter' object has no attribute 'ratelimit'
[2025-10-07T10:17:10.525+0000] {logging_mixin.py:190} INFO - ⚠️ Lỗi khi xử lý ABS: 'Limiter' object has no attribute 'ratelimit'
[2025-10-07T10:17:10.525+0000] {logging_mixin.py:190} INFO - ⚠️ Lỗi khi xử lý ABR: 'Limiter' object has no attribute 'ratelimit'
[2025-10-07T10:17:10.526+0000] {logging_mixin.py:190} INFO - ⚠️ Lỗi khi xử lý ABI: 'Limiter' object has no attribute 'ratelimit'
[2025-10-07T10:17:10.527+0000] {logging_mixin.py:190} INFO - ⚠️ Lỗi khi xử lý ABC: 'Limiter' object has no attribute 'ratelimit'
[2025-10-07T10:17:10.531+0000] {logging_mixin.py:190} INFO - ⚠️ Lỗi khi xử lý ABB: 'Limiter' object has no attribute 'ratelimit'
[2025-10-07T10:17:10.532+0000] {logging_mixin.py:190} INFO - ⚠️ Lỗi khi xử lý AAV: 'Limiter' object has no attribute 'ratelimit'
[2025-10-07T10:17:10.534+0000] {logging_mixin.py:190} INFO - ⚠️ Lỗi khi xử lý AAT: 'Limiter' object has no attribute 'ratelimit'
[2025-10-07T10:17:10.534+0000] {logging_mixin.py:190} INFO - ⚠️ Lỗi khi xử lý AAS: 'Limiter' object has no attribute 'ratelimit'
[2025-10-07T10:17:10.535+0000] {logging_mixin.py:190} INFO - ⚠️ Lỗi khi xử lý AAM: 'Limiter' object has no attribute 'ratelimit'
[2025-10-07T10:17:10.536+0000] {logging_mixin.py:190} INFO - ⚠️ Lỗi khi xử lý AAH: 'Limiter' object has no attribute 'ratelimit'
[2025-10-07T10:17:10.537+0000] {logging_mixin.py:190} INFO - ⚠️ Lỗi khi xử lý AAA: 'Limiter' object has no attribute 'ratelimit'
[2025-10-07T10:17:10.538+0000] {logging_mixin.py:190} INFO - ⚠️ Lỗi khi xử lý A32: 'Limiter' object has no attribute 'ratelimit'
[2025-10-07T10:17:10.538+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-10-07T10:17:10.561+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-10-07T10:17:10.565+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=vnstock_weekly_etl_incremental, task_id=process_batch, run_id=manual__2025-10-07T10:01:57.519057+00:00, map_index=34, execution_date=20251007T100157, start_date=20251007T101708, end_date=20251007T101710
[2025-10-07T10:17:10.747+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-07T10:17:10.794+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
